import mysql from 'mysql2/promise';
import Cors from 'cors';

// Initialize CORS middleware
const cors = Cors({
  methods: ['POST'], // Specify allowed methods
  allowedHeaders: ['Content-Type', 'Authorization'], // Specify allowed headers
  origin: 'https://admin-bytewise24.vercel.app', // Replace with your frontend URL
  credentials: true, // Allow cookies if needed
});

// Helper function to run middleware
function runMiddleware(req, res, fn) {
  return new Promise((resolve, reject) => {
    fn(req, res, (result) => {
      if (result instanceof Error) {
        return reject(result);
      }
      return resolve(result);
    });
  });
}

// Create a MySQL connection pool
const db = mysql.createPool({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
});

export default async function handler(req, res) {
  // Enable CORS for this API route
  await runMiddleware(req, res, cors);

  // Handle OPTIONS request (preflight)
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.setHeader('Access-Control-Allow-Origin', 'https://admin-bytewise24.vercel.app'); // Replace with your frontend URL
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    return res.status(200).end(); // Preflight response
  }

  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  const { description, amount, expense_date, payment_by } = req.body;

  // Validate required fields
  if (!expenses_items || !expenses_amount || !expense_date || !payment_by) {
    return res.status(400).json({ error: "All fields are required" });
  }

  try {
    // Insert the expense into the database
    const query = `
      INSERT INTO bytewise_db.expenses (expenses_items, expenses_amount, expenses_date, payment_by)
      VALUES (?, ?, ?, ?)
    `;
    const [result] = await db.query(query, [
     expenses_items,
      expenses_amount,
      expenses_date,
      payment_by,
    ]);

    // Send the response with the expense details and a serial number as expenseID
    res.status(201).json({
      expensesID: result.insertId, // This is the serial number generated by MySQL
      expenses_items,
      expenses_amount,
      expenses_date,
      payment_by,
    });
  } catch (err) {
    console.error("Error saving expense:", err);
    res.status(500).json({ error: "Failed to save expense" });
  }
}
